### PR TITLE
Alignment score

### PR DESCRIPTION
**Pull request by rob-p**
This PR adds a function `map_with_name` which allows resolving https://github.com/jguhlin/minimap2-rs/issues/75.  Specifically, it passes the query name (which must be `\0` terminated) to the map function, which allows the internal minimap2 function `mm_map` to resolve ties in the chain score.

Though the differences are subtle, this allows exactly replicating the behavior of command-line minimap2, in cases where this tie breaking can result in some alignments being marked supplementary, where they otherwise would not.

### CODE REVIEW

**Comment by mbhall88** [comment]
Hi all,

Just wondering what the status is of this PR? What needs to be done to get it over the line? I'm happy to try and help if necessary.

**Comment by jguhlin** [comment]
@rob-p @mbhall88 Hey. I'll work on getting this all moved today/tomorrow. Got off track with grant writing and some moving plans. :/

**Comment by mbhall88** [comment]
> Got off track with grant writing and some moving plans. :/

Ohhhhh I know the feeling! Thanks so much for this great library/bindings. I'm about to start a project using this library so I'll probably be harassing you a bit over the next couple of weeks 😅

**Comment by rob-p** [comment]
@mbhall88,

  If you want to take a stab at this (https://github.com/jguhlin/minimap2-rs/issues/71), I’m willing to help. Since I found a work around, it’s not top priority for us right now, but it seems important for the lib in general moving forward.

—Rob

**Comment by jguhlin** [comment]
I'm going to merge this, and reconcile with with #85 and then see if I can hack out Arc and push a release

**Pull request merged**
